/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/{adminSlug}/meeting-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminMeetingTypes_list"];
        put?: never;
        post: operations["AdminMeetingTypes_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/{adminSlug}/meeting-types/{meetingTypeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["AdminMeetingTypes_updateStatus"];
        trace?: never;
    };
    "/admin/{adminSlug}/meetings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminMeetings_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/{adminSlug}/meetings/{meetingId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["AdminMeetingActions_updateStatus"];
        trace?: never;
    };
    "/client/{ownerSlug}/meeting-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ClientMeetingTypes_listActive"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/client/{ownerSlug}/meeting-types/{meetingTypeSlug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ClientMeetingTypes_getBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/client/{ownerSlug}/meeting-types/{meetingTypeSlug}/meetings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ClientSlots_listOccupied"];
        put?: never;
        post: operations["ClientMeetings_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "Admin.CreateMeetingTypeRequest": {
            name: string;
            description: string;
            availableFrom: string;
            availableTo: string;
            /** Format: int32 */
            durationMinutes: number;
            slug: string;
            isActive: boolean;
        };
        "Admin.MeetingResponse": {
            /** Format: uuid */
            id: string;
            meetingType: components["schemas"]["Admin.MeetingTypeResponse"];
            /** Format: date-time */
            startDateTime: string;
            comment: string;
            initiator: components["schemas"]["Participant"];
            isConfirmed?: boolean;
            participants: components["schemas"]["Participant"][];
        };
        "Admin.MeetingStatusUpdate": {
            isConfirmed: boolean;
        };
        "Admin.MeetingTypeResponse": {
            /** Format: uuid */
            id: string;
            /** @example Личное напоминание про масло */
            name: string;
            /** @example Напоминание о смене масла в автомобиле */
            description: string;
            /** @example 09:00 */
            availableFrom: string;
            /** @example 18:00 */
            availableTo: string;
            /**
             * Format: int32
             * @example 10
             */
            durationMinutes: number;
            /** @example personal-oil-change */
            slug: string;
            /** @example true */
            isActive: boolean;
        };
        "Admin.MeetingTypeStatusUpdate": {
            /** @example true */
            isActive: boolean;
        };
        "Client.ClientMeetingResponse": {
            meetingType: components["schemas"]["Client.ClientMeetingTypeResponse"];
            /** Format: date-time */
            startDateTime: string;
            /** Format: date-time */
            endDateTime: string;
        };
        "Client.ClientMeetingTypeResponse": {
            owner: components["schemas"]["Client.ClientOwnerResponse"];
            /** @example Личное напоминание про масло */
            name: string;
            /** @example Напоминание о смене масла */
            description: string;
            /** @example 09:00 */
            availableFrom: string;
            /** @example 18:00 */
            availableTo: string;
            /**
             * Format: int32
             * @example 10
             */
            durationMinutes: number;
            /** @example personal-oil-change */
            slug: string;
        };
        "Client.ClientOwnerResponse": {
            /** @example Evgeny */
            name: string;
            /** @example evgeny */
            clientSlug: string;
            /** @example Europe/Moscow */
            timeZone: string;
        };
        "Client.CreateMeetingRequest": {
            /** Format: date-time */
            startDateTime: string;
            comment?: string;
            participants: components["schemas"]["Client.CreateParticipantRequest"][];
        };
        "Client.CreateParticipantRequest": {
            name: string;
            /** Format: email */
            email: string;
        };
        Meeting: {
            /** Format: uuid */
            id: string;
            meetingType: components["schemas"]["MeetingType"];
            /** Format: date-time */
            startDateTime: string;
            comment: string;
            initiator: components["schemas"]["Participant"];
            isConfirmed?: boolean;
        };
        MeetingParticipant: {
            participant: components["schemas"]["Participant"];
            meeting: components["schemas"]["Meeting"];
        };
        MeetingType: {
            /** Format: uuid */
            id: string;
            owner: components["schemas"]["Owner"];
            /** @example Личное напоминание про масло */
            name: string;
            /** @example Напоминание о смене масла в автомобиле */
            description: string;
            /** @default 09:00 */
            availableFrom: string;
            /** @default 18:00 */
            availableTo: string;
            /**
             * Format: int32
             * @example 30
             */
            durationMinutes: number;
            /** @example personal-oil-change */
            slug: string;
            /** @example true */
            isActive: boolean;
        };
        Owner: {
            /** Format: uuid */
            id: string;
            /** @example Evgeny */
            name: string;
            /** @example evgeny-admin */
            adminSlug: string;
            /** @example evgeny */
            clientSlug: string;
        };
        Participant: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: email */
            email: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AdminMeetingTypes_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                adminSlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Admin.MeetingTypeResponse"][];
                };
            };
        };
    };
    AdminMeetingTypes_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                adminSlug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Admin.CreateMeetingTypeRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Admin.MeetingTypeResponse"];
                };
            };
        };
    };
    AdminMeetingTypes_updateStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                adminSlug: string;
                meetingTypeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Admin.MeetingTypeStatusUpdate"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Admin.MeetingTypeResponse"];
                };
            };
        };
    };
    AdminMeetings_list: {
        parameters: {
            query?: {
                dateStartFrom?: string;
                dateStartTo?: string;
                isConfirmed?: boolean;
            };
            header?: never;
            path: {
                adminSlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Admin.MeetingResponse"][];
                };
            };
        };
    };
    AdminMeetingActions_updateStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                adminSlug: string;
                meetingId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Admin.MeetingStatusUpdate"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Admin.MeetingResponse"];
                };
            };
        };
    };
    ClientMeetingTypes_listActive: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ownerSlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Client.ClientMeetingTypeResponse"][];
                };
            };
        };
    };
    ClientMeetingTypes_getBySlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ownerSlug: string;
                meetingTypeSlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Client.ClientMeetingTypeResponse"];
                };
            };
        };
    };
    ClientSlots_listOccupied: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ownerSlug: string;
                meetingTypeSlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Client.ClientMeetingResponse"][];
                };
            };
        };
    };
    ClientMeetings_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ownerSlug: string;
                meetingTypeSlug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Client.CreateMeetingRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Client.ClientMeetingResponse"];
                };
            };
        };
    };
}
